### ISSUE TITLE
All Blueair entities no longer available

### ISSUE THREAD

**Issue by drbuenger** [dahlb/ha_blueair#199]
## System Information

version | core-2025.2.4
-- | --
installation_type | Home Assistant OS

dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.73-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4986
Installed Version | 2.0.5
Stage | running
Available Repositories | 1546
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 5, 2025 at 4:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-11.ui.nabu.casa
certificate_status | ready
instance_id | a7dbe11b8e6242629f1a7cc9eba40927
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.2
-- | --
update_channel | stable
supervisor_version | supervisor-2025.02.1
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 9.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Get HACS (1.3.1), Firefox (Edge) (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 5
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp0s18 (enabled, default, auto), docker0 (disabled), hassio (disabled), veth9b4a46d (disabled), veth73ffa33 (disabled), vethb908e19 (disabled), veth9b890fb (disabled), vethb6c3c7d (disabled), vethba415a7 (disabled), veth942d0b1 (disabled), vetha9c4197 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp0s18 (192.168.0.47/24), docker0 (172.30.232.1/23), hassio (172.30.32.1/23), veth9b4a46d (), veth73ffa33 (), vethb908e19 (), veth9b890fb (), vethb6c3c7d (), vethba415a7 (), veth942d0b1 (), vetha9c4197 ()
ipv6_addresses | lo (::1/128), enp0s18 (fe80::7b00:8bfa:72a:7d6/64), docker0 (fe80::42:ffff:fe79:fb15/64), hassio (fe80::42:ccff:fe23:2ed3/64), veth9b4a46d (fe80::a4fb:79ff:fe0e:a73d/64), veth73ffa33 (fe80::683d:cff:fe8c:8b96/64), vethb908e19 (fe80::ecdb:cfff:fe1c:356b/64), veth9b890fb (fe80::8fb:9fff:fec6:e900/64), vethb6c3c7d (fe80::43b:51ff:fe9c:8682/64), vethba415a7 (fe80::4c84:53ff:fe5c:58eb/64), veth942d0b1 (fe80::dcf6:50ff:fefa:5278/64), vetha9c4197 (fe80::dcaa:d1ff:fe9c:c13d/64)
announce_addresses | 192.168.0.47, fe80::7b00:8bfa:72a:7d6

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 28, 2025 at 11:02 PM
-- | --
current_recorder_run | February 17, 2025 at 9:10 AM
estimated_db_size | 64.59 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_blueair/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The Blueair integration has stopped finding any entities and all entities are listed as Not Available.  I noticed after updating HAOS to 2025.2.4 but I'm unsure if it was working prior to updating.  In the log file I'm seeing many traceback errors and it seems that I've broken my installation. 

### Reproduction steps

1. Restart Home Assistant
2. Restart BlueAir integration
3. All previously working entities now show unavailable
...

### Debug logs

```text
[home-assistant_ha_blueair_2025-02-17T17-11-35.867Z.log](https://github.com/user-attachments/files/18829463/home-assistant_ha_blueair_2025-02-17T17-11-35.867Z.log)
```

### Diagnostics dump

[config_entry-ha_blueair-01JJ82PADBYXJN82ESTZD5R0WQ.json](https://github.com/user-attachments/files/18829464/config_entry-ha_blueair-01JJ82PADBYXJN82ESTZD5R0WQ.json)

**Comment by dahlb** [comment]
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:609
integration: Switch (documentation, issues)
First occurred: 12:28:28 PM (4 occurrences)
Last logged: 12:28:28 PM

Error adding entity None for domain switch with platform ha_blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 609, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 778, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/entity.py", line 52, in device_info
    model=self.coordinator.model,
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/blueair_update_coordinator_device_aws.py", line 17, in model
    return self.blueair_api_device.model.model_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelEnum' object has no attribute 'model_name'

**Comment by wpfog** [comment]
I suddenly had the same problem today. After restarting HA, I get the following error message from the integration:

`“Setup error, will try again: Login failure”`

So it's probably due to the server connection to the Blueair cloud. The manufacturer's app works normally.

**Comment by wpfog** [comment]
@dahlb That is strange. Because I didn't change anything in the configuration and after updating to 1.29.1 the integration somehow stopped working. Since then I only get the login error.
